// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Data;

#nullable disable

namespace WebApp.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240803014540_createBookTableAndSeeding")]
    partial class createBookTableAndSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApp.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Greenwich",
                            CategoryId = 1,
                            Description = "Basic guidance",
                            Price = 100.0,
                            Title = "Programming"
                        },
                        new
                        {
                            Id = 2,
                            Author = "FPT",
                            CategoryId = 1,
                            Description = "Fundamental course for IT",
                            Price = 100.0,
                            Title = "Data Structures"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Greenwich",
                            CategoryId = 1,
                            Description = "Advanced application guidance",
                            Price = 100.0,
                            Title = "App Dev"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Some one",
                            CategoryId = 2,
                            Description = "Good anime",
                            Price = 100.0,
                            Title = "One Piece"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Best Author",
                            CategoryId = 3,
                            Description = "adventure, so fun",
                            Price = 100.0,
                            Title = "Robinhood"
                        });
                });

            modelBuilder.Entity("WebApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayPriority")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Funny",
                            DisplayPriority = 1,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Romantic",
                            DisplayPriority = 4,
                            Name = "Roman"
                        },
                        new
                        {
                            Id = 3,
                            Description = "So scary",
                            DisplayPriority = 2,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 4,
                            Description = "You will love it",
                            DisplayPriority = 3,
                            Name = "Scifi"
                        });
                });

            modelBuilder.Entity("WebApp.Models.Book", b =>
                {
                    b.HasOne("WebApp.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
